config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  resources :posts
  devise_for :users
  resources :users
  root 'movies#index'
  resources :movies do
    resources :comments
    resources :orders
  end
  resources :cards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer_order.rb
class BuyerOrder
  include ActiveModel::Model
  attr_accessor :user_id,:movie_id,:postal_code,:prefecture_id,:municipalities,:address,:building_name,:phone_number
  # ここにバリデーションの処理を書く
  with_options presence: true do
    validates :user_id
    validates :movie_id
    validates :postal_code,format:{with:/\A\d{3}[-]\d{4}\z/}
    validates :prefecture_id, numericality: { other_than: 1}
    validates :municipalities,format:{with:/\A[一-龥ぁ-ん]/}
    validates :address
    validates :phone_number,format:{with:/\A\d{11}\z/}
  end

  def save
    order = Order.create(user_id: user_id,movie_id: movie_id)
    Address.create(postal_code: postal_code,prefecture_id: prefecture_id,municipalities: municipalities,address:address, building_name:building_name,phone_number: phone_number,order_id: order.id)
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :content, presence: true 
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_one_attached :video
  has_many :comments,dependent: :destroy

  with_options presence: true do
    validates :title
    validates :explanation
    validates :video
    validates :price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :address   
  belongs_to :user    
  belongs_to :movie
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :video, VideoUploader
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '--' },
    {id: 2, name: '北海道'}, 
    {id: 3, name: '青森県'},
    {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'},
    {id: 6, name: '秋田県'},
    {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, 
    {id: 9, name: '茨城県'}, 
    {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, 
    {id: 12, name: '埼玉県'}, 
    {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, 
    {id: 15, name: '神奈川県'}, 
    {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, 
    {id: 18, name: '石川県'}, 
    {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, 
    {id: 21, name: '長野県'}, 
    {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, 
    {id: 24, name: '愛知県'}, 
    {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, 
    {id: 27, name: '京都府'}, 
    {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, 
    {id: 30, name: '奈良県'}, 
    {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, 
    {id: 33, name: '島根県'}, 
    {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, 
    {id: 36, name: '山口県'}, 
    {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, 
    {id: 39, name: '愛媛県'}, 
    {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, 
    {id: 42, name: '佐賀県'}, 
    {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, 
    {id: 45, name: '大分県'}, 
    {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, 
    {id: 48, name: '沖縄県'}
]

  include ActiveHash::Associations
  has_many :movies
end

app/models/rule.rb
class Rule < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
    
    ZENNKAKU = /\A[ぁ-んァ-ン一-龥々]+\z/
    ZENNKAKU_KATAKANA = /\A[ァ-ヶー－]+\z/
    with_options presence: true do
    validates :nickname
    validates :familyname,format: { with: ZENNKAKU}
    validates :firstname,format: { with: ZENNKAKU }
    validates :familyname_kana,format: { with: ZENNKAKU_KATAKANA } 
    validates :firstname_kana,format: { with: ZENNKAKU_KATAKANA }
    validates :birthday
    validates :fishing_history
    validates :password,format: { with:  /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
    end

    has_many :movies
    has_many :comments
    has_one :card, dependent: :destroy
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer = Payjp::Customer.create(
    description: 'test', # テストカードであることを説明
    card: params[:card_token] # 登録しようとしているカード情報
    )
    
    card = Card.new( # トークン化されたカード情報を保存する
      card_token: params[:card_token], # カードトークン
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )
    if card.save
      redirect_to root_path
    else
      redirect_to "new" # カード登録画面
    end
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new,:edit,:destroy]

  def index
    @movies = Movie.all.order(id: "DESC")
  end
  

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to root_path
    else
      render :new  
    end
  end  

  def show
    @movie = Movie.find(params[:id])
    if user_signed_in? && current_user.id.present?
      @movie = Movie.find(params[:id])
      @comment = Comment.new
      @comments = @movie.comments.includes(:user)
    else
      redirect_to new_user_registration_path
    end
  end

  def edit
    @movie =Movie.find(params[:id])
    unless @movie.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movie_path
    else
      render :edit
    end
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.destroy
    redirect_to root_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :explanation,:video,:price).merge(user_id: current_user.id)
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
      @user = User.find(params[:id])
    if user_signed_in? == @user.id.present?
      @movie = @user.movies.order(id: "DESC")
      
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      card = Card.find_by(user_id: current_user.id)
        if card.present?
          customer = Payjp::Customer.retrieve(card.customer_token) # 先程のカード情報を元に、顧客情報を取得
          @card = customer.cards.first
        end
    else
      redirect_to new_user_registration_path
    end
  end
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      redirect_to "show"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'card-form', class: 'card-form',local: true do |f| %>
  <div class="Cardpage">
    <h1>カード登録</h1>
  </div><br>
  <div class='form-wrap'>
    <%= f.label :number, "【カード番号】" %><br>
    <%= f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"25" %>
  </div>
  <div class='form-wrap'>
    <%= f.label :cvc ,"【ＣＶＣ】" %><br>
    <%= f.text_field :cvc, class:"cvc", placeholder:"カード背面にある3桁の番号", maxlength:"10" %>
  </div>
  <div class='form-wrap'>
  <br>
    <p>【有効期限】</p>
    <div class='input-expiration-date-wrap'>
      <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "exp_month" %>
      <p>月</p>
      <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "exp_year" %>
      <p>年</p>
    </div>
  </div>
  <%= f.submit "登録する" , class:"button" %>
<% end %>

app/views/rules/index.html.erb
<h1>利用規約</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %> 

app/views/users/edit.html.erb
<h1>Editing Name</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %> 

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
        <div class="table-main">
          <table class="table1">
            <tbody>
              <tr>
                <th class="table__col1">ニックネーム</th>
                <td class="table__col2"><%= "#{@user.nickname}" %></td>
              </tr>
              <tr>
                <th class="table__col1">釣り歴</th>
                <td class="table__col2"><%= "#{@user.fishing_history}" %></td>
              </tr>
              <tr>
                <th class="table__col1">ターゲット</th>
                <td class="table__col2"><%=  "#{@user.target}" %></td>
              </tr>
              <tr>
                <th class="table__col1">釣り場/フィールド</th>
                <td class="table__col2"><%=  "#{@user.spot}" %></td>
              </tr>
            </tbody>
          </table>
          <table class="table2">
            <tbody>
              <tr>
                <th class="table__col1">メインロッド</th>
                <td class="table__col2"><%=  "#{@user.main_rod}" %></td>
              </tr>
              <tr>
                <th class="table__col1">メインリール</th>
                <td class="table__col2"><%=  "#{@user.main_reel}" %></td>
              </tr>
              <tr>
                <th class="table__col1">自身のブログ等</th>
                <td class="table__col2"><%=  "#{@user.appeal}" %></td>
              </tr>
              <% if current_user.id == @user.id && @card.present?%>
                <tr>
                  <th class="table__col1">カード情報</th>
                  <td class="table__col2"><%=  "**** **** **** " + @card[:last4] %> <%= @card[:exp_month] %>/<%= @card[:exp_year] %> </td>
                </tr>
              <%end%> 
            </tbody>
          </table>
        </div>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの動画"%>
      </h2>
      <div class="user__card">
          <%= render partial: "movies/movie", collection: @movie %>
      </div>
    </div>
  </div>
</div>